"""
Django settings for dummy project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cccoevp@#xmtvi02ty^5(+!0p7hz&rwc=4t(a5x)dc_1f$sx*t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'book.apps.BookConfig',
    'user.apps.UserConfig',
    'author.apps.AuthorConfig',
    'crispy_forms',
    'star_ratings',
    'blog',
    'django_cleanup.apps.CleanupConfig',
    'postman',
    'django.contrib.sites',
    'ckeditor',
    'ckeditor_uploader',
    'taggit',
    'django_comments_xtd',
    'django_comments',
    'friendship',
    'hitcount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.onlinenowMiddelware.OnlineNowMiddleware',
]

ROOT_URLCONF = 'dummy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dummy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#   DJANGO SETTINGS MANUAL


#STATIC SETTINGS
STATIC_URL = '/static/'
STATIC_ROOT = 'static/'

#MEDIA
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

#CRISPY FORMS SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#REDIRECT SETTINGS
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'main'
LOGOUT_REDIRECT_URL = 'main'

#DJANGO MAIL SETTINGS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER='nagavarapradeepyendluri@gmail.com'
EMAIL_HOST_PASSWORD='N@gamani1999'
DEFAULT_FROM_EMAIL = "Helpdesk <helpdesk@zoro>"


#POSTMAN MESSAGES SETTINGS
POSTMAN_AUTO_MODERATE_AS =True

#CKEDITOR APP SETTINGS
CKEDITOR_UPLOAD_PATH = "uploads/"

#TAGGIT APP
TAGGIT_CASE_INSENSITIVE = True

#COMMENTS SETTINGS
COMMENTS_APP = 'django_comments_xtd'
COMMENTS_XTD_MAX_THREAD_LEVEL = 5
COMMENTS_XTD_CONFIRM_EMAIL = True
COMMENTS_XTD_APP_MODEL_OPTIONS = {
    'book.book': {
        'allow_flagging': True,
        'allow_feedback': True,
        'show_feedback': True,
    },
    'book.chapter': {
        'allow_flagging': True,
        'allow_feedback': True,
        'show_feedback': True,
    }
}

#Reidrect site id for postman and comments app change it if you add new site
SITE_ID = 1

#Book View settings


