# Generated by Django 2.2.9 on 2020-01-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
