# Generated by Django 3.0.1 on 2019-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('R', 'Reading...'), ('CC', 'Yet to complete'), ('NS', 'Not Started')], default='NS', max_length=3),
            preserve_default=False,
        ),
    ]
