# Generated by Django 2.2.9 on 2020-02-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200206_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(related_name='chapter', to='book.Chapter'),
        ),
    ]
