# Generated by Django 2.2.9 on 2020-02-02 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_auto_20200201_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='author',
            field=models.ManyToManyField(related_name='chapter_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
