# Generated by Django 3.0.1 on 2019-12-22 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_auto_20191221_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.ManyToManyField(related_name='book_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
