# Generated by Django 2.2.9 on 2020-02-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_chapter_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lang_code',
            field=models.CharField(default='en', max_length=6),
            preserve_default=False,
        ),
    ]
