# Generated by Django 2.2.9 on 2020-01-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200115_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='prog',
            field=models.CharField(choices=[('Read', 'Read'), ('To-be-Read', 'To-be-Read'), ('Now Reading', 'Now Reading')], max_length=32),
        ),
    ]
