# Generated by Django 3.0.1 on 2019-12-22 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_book_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.ManyToManyField(related_name='book_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
