# Generated by Django 3.0.1 on 2019-12-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20191222_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='genrename',
        ),
    ]
