# Generated by Django 3.0.1 on 2019-12-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20191222_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genrename',
            new_name='genre',
        ),
    ]
