# Generated by Django 3.0.1 on 2019-12-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20191222_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2019-03-03'),
            preserve_default=False,
        ),
    ]
