# Generated by Django 3.0.1 on 2019-12-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20191225_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='book_name',
        ),
        migrations.AddField(
            model_name='book',
            name='collection',
            field=models.ManyToManyField(related_name='coll', to='book.Collection'),
        ),
    ]
