# Generated by Django 3.0.1 on 2019-12-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20191225_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='collection',
        ),
    ]
