# Generated by Django 2.2.9 on 2019-12-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_auto_20191226_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
