# Generated by Django 2.2.9 on 2019-12-29 23:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20191229_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ManyToManyField(related_name='book_chapter', to='book.Book'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='chapters'), upload_to=''),
        ),
    ]
