# Generated by Django 2.2.9 on 2019-12-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_auto_20191229_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
    ]
