# Generated by Django 2.2.9 on 2019-12-30 00:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20191229_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/chapters'), upload_to=''),
        ),
    ]
