# Generated by Django 2.2.9 on 2019-12-31 20:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_auto_20191229_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
