# Generated by Django 2.2.9 on 2020-01-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
