# Generated by Django 2.2.9 on 2020-01-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200117_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutme',
            field=models.CharField(default='n', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='America', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='America', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Australia', 'Australia')], default='Not Chosen', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.CharField(default='n', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
