# Generated by Django 3.0.1 on 2019-12-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191221_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
        migrations.DeleteModel(
            name='Read',
        ),
    ]
