# Generated by Django 2.2.9 on 2020-01-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200117_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aboutme',
            field=models.TextField(default='n', max_length=150),
        ),
    ]
