# Generated by Django 3.0.1 on 2019-12-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20191225_0637'),
        ('user', '0004_auto_20191223_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collection',
            field=models.ManyToManyField(related_name='collections', to='book.Collection'),
        ),
    ]
