# Generated by Django 3.0.1 on 2019-12-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191225_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='Book',
            new_name='books',
        ),
    ]
