# Generated by Django 2.2.9 on 2019-12-26 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_auto_20191226_1409'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20191225_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.CharField(default='NR', max_length=4)),
                ('books', models.ManyToManyField(related_name='status', to='book.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
