# Generated by Django 2.2.9 on 2019-12-27 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0022_auto_20191226_1409'),
        ('user', '0008_read'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read',
            new_name='Status',
        ),
    ]
