# Generated by Django 2.2.9 on 2019-12-27 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_auto_20191226_1409'),
        ('user', '0009_auto_20191226_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='books',
        ),
        migrations.AddField(
            model_name='status',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
    ]
