# Generated by Django 2.2.9 on 2019-12-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191226_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='read_status',
            field=models.CharField(choices=[('NR', 'Not Read'), ('R', 'Read'), ('RG', 'Currently Reading'), ('TR', 'Want To Read')], default='NR', max_length=4),
        ),
    ]
