# Generated by Django 2.2.9 on 2019-12-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191226_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
